name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
    inputs:
      suite:
        description: "Test suite to run"
        required: true
        default: "regression"
        type: choice
        options:
          - smoke
          - regression
          - purchase
          - error
          - api

      browser:
        description: "Browser project"
        required: true
        default: "chromium"
        type: choice
        options:
          - chromium
          - firefox
          - webkit

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: npm

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Clean Allure Results
      run: npm run allure:clean

      # Push/Pull Request
    - name: Run Regression Tests
      if: github.event_name != 'workflow_dispatch'
      run: npm run test:regression -- --project=chromium

      # Manual Github Actions run
    - name: Run Selected Suite
      if: github.event_name == 'workflow_dispatch'
      run: npm run test:${{ inputs.suite }} -- --project=${{ inputs.browser }}

    - name: Generate Allure Report
      if: ${{ !cancelled() }}
      run: npm run allure:generate
      
    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-${{ inputs.suite }}-${{ inputs.browser }}
        path: playwright-report/
        retention-days: 30

    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: allure-report
        path: allure-report/
        retention-days: 30
